import {useEffect,useMemo,useState} from 'react';
import {useAuth} from '../context/AuthContext';
import {fetchPortal,gameAction} from '../lib/gameApi';
import {Backpack,Castle,Flame,Gift,Mail,MessageCircle,RefreshCw,ScrollText,Shield,ShoppingBag,Sparkles,Swords,Trophy} from 'lucide-react';
const tabs=[['profile','Tiên Phủ',Sparkles],['trade','Tiên Thị',ShoppingBag],['sect','Tông Môn',Castle],['boss','Boss TG',Flame],['event','Thú Triều',Swords],['sectwar','Tông Chiến',Shield],['season','Season',Trophy],['mail','Tiên Thư',Mail],['chat','Truyền Âm',MessageCircle],['guide','Hướng Dẫn',ScrollText]];
const n=x=>Number(x||0).toLocaleString();
function Result({notice}){return notice?<div className="portal-notice">{notice}</div>:null}
export default function GameHub(){const{session,user,signInDiscord}=useAuth();const[token]=useState(()=>session?.access_token);const[tab,setTab]=useState('profile'),[data,setData]=useState(null),[guilds,setGuilds]=useState([]),[guildId,setGuildId]=useState(localStorage.getItem('ci-game-guild')||''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const access=session?.access_token||token;async function load(g=guildId){if(!access)return;setBusy(true);try{const r=await fetchPortal(access,g);setData(r);setGuilds([]);if(r.guild?.id&&!g){setGuildId(r.guild.id);localStorage.setItem('ci-game-guild',r.guild.id)}}catch(e){if(e.status===409&&e.data?.guilds){setGuilds(e.data.guilds);setData(null)}else setNotice(`⚠️ ${e.message}`)}finally{setBusy(false)}}useEffect(()=>{load()},[session?.access_token]);
 async function act(action,params={}){setBusy(true);setNotice('');try{const r=await gameAction(access,data?.player?.guildId||guildId,action,params);const msg=r.result?.content||r.result?.subject||'✅ Hoàn tất.';setNotice(msg);await load(data?.player?.guildId||guildId)}catch(e){setNotice(`⚠️ ${e.message}`);setBusy(false)}}
 if(!user)return <section className="section portal-shell"><div className="portal-hero"><span>☯ TIÊN GIỚI</span><h1>Corgi Immortal</h1><p>Đăng nhập Discord để mở Tiên Phủ và các hệ thống đồng bộ với bot.</p><button className="primary-btn" onClick={signInDiscord}>Đăng nhập Discord</button></div></section>;
 if(guilds.length)return <section className="section portal-shell"><div className="portal-card"><h2>Chọn Tiên Giới</h2><p>Tài khoản có nhân vật ở nhiều server.</p><select onChange={e=>{const id=e.target.value;setGuildId(id);localStorage.setItem('ci-game-guild',id);load(id)}} defaultValue=""><option value="">Chọn server…</option>{guilds.map(g=><option value={g.guildId} key={g.guildId}>{g.name}</option>)}</select></div></section>;
 if(!data)return <section className="section portal-shell"><div className="portal-card">{busy?'Đang khai mở Tiên Phủ…':'Không tải được dữ liệu nhân vật.'}</div><Result notice={notice}/></section>;
 const p=data.player;
 return <section className="section portal-shell"><div className="portal-hero compact"><span>☯ {data.guild?.name}</span><h1>Tiên Phủ • {p.name}</h1><p>{p.realm} · Chiến lực {n(p.power)} · {n(p.spiritStones)} Linh Thạch</p><button className="ghost-btn" onClick={()=>load(p.guildId)} disabled={busy}><RefreshCw size={15}/> Làm mới</button></div><div className="portal-tabs">{tabs.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={16}/>{label}</button>)}</div><Result notice={notice}/>
 {tab==='profile'&&<Profile p={p}/>} {tab==='trade'&&<Trade data={data} act={act} busy={busy}/>} {tab==='sect'&&<Sect data={data} act={act} busy={busy}/>} {tab==='boss'&&<Boss data={data} act={act} busy={busy}/>} {tab==='event'&&<Event data={data} act={act} busy={busy}/>} {tab==='sectwar'&&<SectWar data={data} act={act} busy={busy}/>} {tab==='season'&&<Season data={data} act={act} busy={busy}/>} {tab==='mail'&&<Mails data={data} act={act} busy={busy}/>} {tab==='chat'&&<Chat data={data} act={act} busy={busy}/>} {tab==='guide'&&<Guide/>}</section>}
function Profile({p}){return <div className="portal-grid"><div className="portal-card span2"><h2>📜 Hồ Sơ Tu Hành</h2><div className="stat-grid"><Stat k="Cảnh giới" v={p.realm}/><Stat k="Tu vi" v={`${n(p.cultivation)} / ${n(p.requiredCultivation)}`}/><Stat k="Chiến lực" v={n(p.power)}/><Stat k="Linh Thạch" v={n(p.spiritStones)}/><Stat k="Linh Căn" v={p.spiritRoot||'Chưa thức tỉnh'}/><Stat k="Thể Chất" v={p.physique||'Phàm Thể'}/><Stat k="Cống Hiến" v={n(p.contribution)}/><Stat k="Danh Vọng" v={n(p.prestige)}/></div></div><div className="portal-card span2"><h2><Backpack size={19}/> Túi Càn Khôn</h2><div className="item-list">{p.inventory?.length?p.inventory.map(x=><div className="item-row" key={x.slot}><b>#{x.slot} {x.name}</b><span>{x.grade} · ×{x.qty}{x.equipped?' · Đang trang bị':''}</span></div>):<p>Túi đồ trống.</p>}</div></div></div>}
function Trade({data,act,busy}){const[sell,setSell]=useState({slot:'',price:''}),[auc,setAuc]=useState({slot:'',price:''}),[bid,setBid]=useState({id:'',amount:''});return <div className="portal-grid"><div className="portal-card"><h2>💎 Phường Thị</h2><div className="portal-form"><input placeholder="Slot vật phẩm" value={sell.slot} onChange={e=>setSell({...sell,slot:e.target.value})}/><input placeholder="Giá bán" value={sell.price} onChange={e=>setSell({...sell,price:e.target.value})}/><button disabled={busy} onClick={()=>act('market_sell',{slot:+sell.slot,price:+sell.price})}>Đăng bán</button></div>{data.market.map(x=><div className="listing" key={x._id}><div><b>{x.item?.name}</b><small>{x.item?.rarity||x.item?.grade}</small></div><strong>{n(x.price)} 💎</strong><button disabled={busy||x.sellerId===data.player.userId} onClick={()=>act('market_buy',{id:x._id})}>Mua</button></div>)}</div><div className="portal-card"><h2>🔨 Đấu Giá</h2><div className="portal-form"><input placeholder="Slot" value={auc.slot} onChange={e=>setAuc({...auc,slot:e.target.value})}/><input placeholder="Giá mở" value={auc.price} onChange={e=>setAuc({...auc,price:e.target.value})}/><button disabled={busy} onClick={()=>act('auction_create',{slot:+auc.slot,start_price:+auc.price})}>Tạo phiên 6 giờ</button></div>{data.auctions.map(x=><div className="listing" key={x._id}><div><b>{x.item?.name}</b><small>Hết hạn {new Date(x.expiresAt).toLocaleString()}</small></div><strong>{n(x.highestBid||x.price)} 💎</strong><button onClick={()=>setBid({...bid,id:x._id})}>Chọn</button></div>)}<div className="portal-form"><input placeholder="Auction ID" value={bid.id} onChange={e=>setBid({...bid,id:e.target.value})}/><input placeholder="Giá đấu" value={bid.amount} onChange={e=>setBid({...bid,amount:e.target.value})}/><button disabled={busy} onClick={()=>act('auction_bid',{id:bid.id,amount:+bid.amount})}>Ra giá</button></div></div></div>}
function Sect({data,act,busy}){const[name,setName]=useState(''),[amount,setAmount]=useState('');return <div className="portal-grid"><div className="portal-card"><h2>🏯 Tông Môn của ta</h2>{data.mySect?<><h3>{data.mySect.name}</h3><p>Lv.{data.mySect.level} · {data.mySect.members} thành viên · Kho {n(data.mySect.treasury)}</p><p>{data.mySect.description||'Tông môn chưa có mô tả.'}</p><div className="portal-form"><input placeholder="Linh Thạch cống hiến" value={amount} onChange={e=>setAmount(e.target.value)}/><button disabled={busy} onClick={()=>act('sect_donate',{amount:+amount})}>Cống hiến</button><button disabled={busy} onClick={()=>act('sect_cultivate')}>Tu luyện Tông Môn</button></div></>:<><p>Chưa gia nhập Tông Môn.</p><div className="portal-form"><input placeholder="Tên Tông Môn" value={name} onChange={e=>setName(e.target.value)}/><button disabled={busy} onClick={()=>act('sect_join',{name})}>Gia nhập</button><button disabled={busy} onClick={()=>act('sect_create',{name})}>Lập Tông (2,000 💎)</button></div></>}</div><div className="portal-card"><h2>📜 Danh Sách Tông Môn</h2>{data.sects.map(s=><button className="sect-row" key={s._id} onClick={()=>setName(s.name)}><b>{s.name}</b><span>Lv.{s.level} · {s.members} thành viên · Kho {n(s.treasury)}</span></button>)}</div></div>}
function Boss({data,act,busy}){const b=data.boss;return <div className="portal-card"><h2>👹 Boss Thế Giới</h2>{!b?<p>Chưa có Boss.</p>:<><h3>{b.name}</h3><div className="hp"><i style={{width:`${Math.max(0,Math.min(100,b.hp/b.maxHp*100))}%`}}/></div><p>❤️ {n(b.hp)} / {n(b.maxHp)} · {b.state}</p><button className="primary-btn" disabled={busy||b.state!=='OPEN'} onClick={()=>act('boss_attack')}>⚔️ Tấn công Boss</button><Ranking rows={b.top}/></>}</div>}
function Event({data,act,busy}){const e=data.event;return <div className="portal-card"><h2>🌌 Thú Triều / Thiên Biến</h2>{!e?<p>Chưa có biến cố.</p>:<><h3>{e.name} · Lv.{e.level}</h3><p>Tiến độ {n(e.progress)} / {n(e.goal)} · Quỹ {n(e.rewardPool)} 💎</p><button className="primary-btn" disabled={busy||!e.active} onClick={()=>act('worldevent_join')}>⚔️ Tham chiến</button><Ranking rows={e.top}/></>}</div>}
function SectWar({data,act,busy}){return <div className="portal-card"><h2>🏯 Tông Chiến</h2><p>Chiến công cá nhân: <b>{n(data.sectWar?.contribution)}</b></p><p>Tông Môn: <b>{data.mySect?.name||'Chưa gia nhập'}</b></p><button className="primary-btn" disabled={busy||!data.mySect} onClick={()=>act('sectwar_contribute')}>⚔️ Đóng góp chiến lực</button></div>}
function Season({data,act,busy}){const s=data.season,xp=s.xp%s.xpPerLevel;return <div className="portal-card"><h2>🌙 {s.name}</h2><p>Season Pass Lv.<b>{s.level}/{s.maxLevel}</b> · {n(xp)}/{n(s.xpPerLevel)} XP · {s.premium?'Premium':'Free'}</p><div className="hp season"><i style={{width:`${Math.min(100,xp/s.xpPerLevel*100)}%`}}/></div><div className="portal-actions"><button disabled={busy} onClick={()=>act('season_claim')}>🎁 Nhận mốc kế</button><button disabled={busy} onClick={()=>act('season_claim_all')}>✨ Nhận tất cả</button></div><h3>Nhật Nhiệm</h3>{Object.entries(s.daily).map(([k,v])=><p key={k}>{v.name}: <b>{s.dailyProgress?.[k]||0}/{v.target}</b> · +{v.xp} XP</p>)}<h3>Chu Nhiệm</h3>{Object.entries(s.weekly).map(([k,v])=><p key={k}>{v.name}: <b>{s.weeklyProgress?.[k]||0}/{v.target}</b> · +{v.xp} XP</p>)}</div>}
function Mails({data,act,busy}){return <div className="portal-card"><h2>✉️ Tiên Thư</h2>{data.mails.length?data.mails.map(m=><div className="mail-row" key={m._id}><div><b>{m.claimed?'✅':'📩'} {m.subject}</b><p>{m.body}</p></div>{!m.claimed&&<button disabled={busy} onClick={()=>act('mail_claim',{id:m._id})}>Nhận quà</button>}</div>):<p>Không có thư.</p>}</div>}
function Chat({data,act,busy}){const[msg,setMsg]=useState('');return <div className="portal-card"><h2>💬 Truyền Âm Các</h2>{!data.chat?.configured?<p>Kênh truyền âm chưa được Server Owner cấu hình. Hệ thống sẽ dùng kênh Journey/Announcement làm fallback khi có.</p>:<><div className="chat-feed">{data.chat.messages.map(m=><div className="chat-msg" key={m.id}>{m.avatar&&<img src={m.avatar}/>}<div><b>{m.name}</b><p>{m.content}</p></div></div>)}</div><div className="chat-compose"><input maxLength={300} value={msg} onChange={e=>setMsg(e.target.value)} placeholder="Truyền âm tới Discord…"/><button disabled={busy||!msg.trim()} onClick={async()=>{await act('chat_send',{message:msg});setMsg('')}}>Gửi</button></div></>}</div>}
function Guide(){return <div className="portal-grid"><div className="portal-card"><h2>📖 Hướng Dẫn</h2><p><b>Tiên Thị:</b> đăng bán, mua và đấu giá dùng cùng vật phẩm/Linh Thạch với Discord.</p><p><b>Tông Môn:</b> xem danh sách, gia nhập, lập tông, cống hiến và tu luyện.</p><p><b>Boss / Thú Triều / Tông Chiến:</b> thao tác tại đây dùng đúng logic và cooldown của bot.</p><p><b>Season / Tiên Thư:</b> tiến độ và phần thưởng đồng bộ tức thì.</p></div><div className="portal-card"><h2>🔐 Đồng bộ an toàn</h2><p>Web xác thực phiên Discord trước khi API tìm Player. Trình duyệt không được tự chọn userId hay chỉnh số dư.</p></div></div>}
function Ranking({rows=[]}){return <div className="ranking-mini">{rows.map(r=><div key={r.userId}><span>#{r.rank} {r.userId}</span><b>{n(r.value)}</b></div>)}</div>}
function Stat({k,v}){return <div className="stat"><span>{k}</span><b>{v}</b></div>}
